// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionOrdersReact.Server.Data;

#nullable disable

namespace SolutionOrdersReact.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260103133701_OrderWithOrderItemsAndWorkersMigration")]
    partial class OrderWithOrderItemsAndWorkersMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            IdCategory = 1,
                            Description = "Urządzenia elektroniczne",
                            IsActive = true,
                            Name = "Elektronika"
                        },
                        new
                        {
                            IdCategory = 2,
                            Description = "Produkty spożywcze",
                            IsActive = true,
                            Name = "Żywność"
                        },
                        new
                        {
                            IdCategory = 3,
                            Description = "Ubrania i akcesoria",
                            IsActive = true,
                            Name = "Odzież"
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            Address = "ul. Główna 1",
                            City = "Warszawa",
                            Email = "jan.kowalski@email.com",
                            FirstName = "Jan",
                            IsActive = true,
                            LastName = "Kowalski",
                            Phone = "123456789",
                            PostalCode = "00-001"
                        },
                        new
                        {
                            IdClient = 2,
                            Address = "ul. Rynek 5",
                            City = "Kraków",
                            Email = "anna.nowak@email.com",
                            FirstName = "Anna",
                            IsActive = true,
                            LastName = "Nowak",
                            Phone = "987654321",
                            PostalCode = "30-001"
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<int?>("IdUnitOfMeasurement")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("IdItem");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdUnitOfMeasurement");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            IdItem = 1,
                            Code = "LAP001",
                            Description = "Laptop Dell Inspiron 15",
                            IdCategory = 1,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Laptop Dell",
                            Price = 3500m,
                            Quantity = 10m
                        },
                        new
                        {
                            IdItem = 2,
                            Code = "MON001",
                            Description = "Monitor 24 cale",
                            IdCategory = 1,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Monitor Samsung",
                            Price = 800m,
                            Quantity = 15m
                        },
                        new
                        {
                            IdItem = 3,
                            Code = "MYS001",
                            Description = "Mysz bezprzewodowa",
                            IdCategory = 1,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Mysz Logitech",
                            Price = 150m,
                            Quantity = 50m
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<DateTime?>("DataOrder")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdWorker")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdWorker");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            IdOrder = 1,
                            DataOrder = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClient = 1,
                            IdWorker = 1,
                            IsActive = true,
                            Notes = "Pierwsze zamówienie testowe"
                        },
                        new
                        {
                            IdOrder = 2,
                            DataOrder = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClient = 2,
                            IdWorker = 2,
                            IsActive = true,
                            Notes = "Drugie zamówienie testowe"
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.OrderItem", b =>
                {
                    b.Property<int>("IdOrderItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrderItem"));

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdOrderItem");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdOrder");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            IdOrderItem = 1,
                            IdItem = 1,
                            IdOrder = 1,
                            IsActive = true,
                            Quantity = 2m,
                            UnitPrice = 3500m
                        },
                        new
                        {
                            IdOrderItem = 2,
                            IdItem = 2,
                            IdOrder = 1,
                            IsActive = true,
                            Quantity = 3m,
                            UnitPrice = 800m
                        },
                        new
                        {
                            IdOrderItem = 3,
                            IdItem = 3,
                            IdOrder = 2,
                            IsActive = true,
                            Quantity = 5m,
                            UnitPrice = 150m
                        },
                        new
                        {
                            IdOrderItem = 4,
                            IdItem = 1,
                            IdOrder = 2,
                            IsActive = true,
                            Quantity = 1m,
                            UnitPrice = 3500m
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("IdUnitOfMeasurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnitOfMeasurement"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUnitOfMeasurement");

                    b.ToTable("UnitOfMeasurements");

                    b.HasData(
                        new
                        {
                            IdUnitOfMeasurement = 1,
                            Description = "Sztuki",
                            IsActive = true,
                            Name = "szt"
                        },
                        new
                        {
                            IdUnitOfMeasurement = 2,
                            Description = "Kilogramy",
                            IsActive = true,
                            Name = "kg"
                        },
                        new
                        {
                            IdUnitOfMeasurement = 3,
                            Description = "Litry",
                            IsActive = true,
                            Name = "l"
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Worker", b =>
                {
                    b.Property<int>("IdWorker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWorker"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdWorker");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            IdWorker = 1,
                            Address = "ul. Handlowa 10",
                            City = "Warszawa",
                            Email = "piotr.wisniewski@firma.pl",
                            FirstName = "Piotr",
                            IsActive = true,
                            LastName = "Wiśniewski",
                            Phone = "111222333",
                            PostalCode = "00-100"
                        },
                        new
                        {
                            IdWorker = 2,
                            Address = "ul. Biurowa 15",
                            City = "Kraków",
                            Email = "maria.zielinska@firma.pl",
                            FirstName = "Maria",
                            IsActive = true,
                            LastName = "Zielińska",
                            Phone = "444555666",
                            PostalCode = "30-100"
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Item", b =>
                {
                    b.HasOne("SolutionOrdersReact.Server.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionOrdersReact.Server.Models.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("Items")
                        .HasForeignKey("IdUnitOfMeasurement")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Order", b =>
                {
                    b.HasOne("SolutionOrdersReact.Server.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SolutionOrdersReact.Server.Models.Worker", "Worker")
                        .WithMany("Orders")
                        .HasForeignKey("IdWorker")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.OrderItem", b =>
                {
                    b.HasOne("SolutionOrdersReact.Server.Models.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionOrdersReact.Server.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Item", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.UnitOfMeasurement", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Worker", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
