// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionOrdersReact.Server.Data;

#nullable disable

namespace SolutionOrdersReact.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            IdCategory = 1,
                            Description = "Urządzenia elektroniczne",
                            IsActive = true,
                            Name = "Elektronika"
                        },
                        new
                        {
                            IdCategory = 2,
                            Description = "Produkty spożywcze",
                            IsActive = true,
                            Name = "Żywność"
                        },
                        new
                        {
                            IdCategory = 3,
                            Description = "Ubrania i akcesoria",
                            IsActive = true,
                            Name = "Odzież"
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            City = "Warszawa",
                            Email = "jan.kowalski@email.com",
                            FirstName = "Jan",
                            IsActive = true,
                            LastName = "Kowalski",
                            Phone = "123456789"
                        },
                        new
                        {
                            IdClient = 2,
                            City = "Kraków",
                            Email = "anna.nowak@email.com",
                            FirstName = "Anna",
                            IsActive = true,
                            LastName = "Nowak",
                            Phone = "987654321"
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<int?>("IdUnitOfMeasurement")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("IdItem");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdUnitOfMeasurement");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            IdItem = 1,
                            Code = "LAP001",
                            Description = "Laptop Dell Inspiron 15",
                            IdCategory = 1,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Laptop Dell",
                            Price = 3500m,
                            Quantity = 10m
                        },
                        new
                        {
                            IdItem = 2,
                            Code = "MON001",
                            Description = "Monitor 24 cale",
                            IdCategory = 1,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Monitor Samsung",
                            Price = 800m,
                            Quantity = 15m
                        },
                        new
                        {
                            IdItem = 3,
                            Code = "MYS001",
                            Description = "Mysz bezprzewodowa",
                            IdCategory = 1,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Mysz Logitech",
                            Price = 150m,
                            Quantity = 50m
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("IdUnitOfMeasurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnitOfMeasurement"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUnitOfMeasurement");

                    b.ToTable("UnitOfMeasurements");

                    b.HasData(
                        new
                        {
                            IdUnitOfMeasurement = 1,
                            Description = "Sztuki",
                            IsActive = true,
                            Name = "szt"
                        },
                        new
                        {
                            IdUnitOfMeasurement = 2,
                            Description = "Kilogramy",
                            IsActive = true,
                            Name = "kg"
                        },
                        new
                        {
                            IdUnitOfMeasurement = 3,
                            Description = "Litry",
                            IsActive = true,
                            Name = "l"
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Item", b =>
                {
                    b.HasOne("SolutionOrdersReact.Server.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionOrdersReact.Server.Models.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("Items")
                        .HasForeignKey("IdUnitOfMeasurement")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.UnitOfMeasurement", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
